# Site settings
title: Academia Lovelace
email: contato@academialovelace.org
description: > # this means to ignore newlines until "baseurl:"
  Academia Lovelace é um projeto sem fins lucrativos para estimular mulheres
  a entrar no mundo de trabalho de desenvolvimento de software através de grupos
  de estudo usando o FreeCodeCamp.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://academialovelace.org" # the base hostname & protocol for your site

# Social media (mainly for footer)
# twitter_username: academialovelace
github_username:  AcademiaLovelace
facebook_username: academialovelace

# Build settings
markdown: kramdown

# Standard timezone
timezone: America/Sao_Paulo
